### ISSUE TITLE
FEATURE: Publish a Poll

### ISSUE THREAD

**Issue by KevinDGnanih** [KevinDGnanih/my-first-agile-project#4]
In order to **collect users' feedback** as an **administrator** I can **publish a poll.**

**Comment by KevinDGnanih** [comment]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll.**

## Acceptance Criteria:

- The poll should disappear at 11:59 PM on the target date#
- The real estate of the "Poll" should be reserved on the home page. A message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
- The administrator expiry date should be at least 3 days after the current date.

## Tasks:

- [x] Update the admin module view: the poll design (HTML and CSS) to include a date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Poll every day at 11:59 PM and hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
